import type { MornDraftReleaseConfig } from '../../../utils/releaseConfigTypes';

export const OSS_RELEASE_CONFIG: MornDraftReleaseConfig = Object.freeze({
  authMode: 'none',
  deliveryPolicyMode: 'publicAllOpen',
  disableAccountPlanQuotaUi: true,
  disableAccountPromoUi: true,
  disableReferralsUi: true,
  disableMcpUi: true,
  disableAiAssistUi: false,
  disableFeedbackUi: true,
  disablePaymentCheckout: true,
  disablePreviewDeliveryActions: false,
  disablePreviewFormatToolbar: false,
  disableSubscriptionUi: true,
  disableHostedLinkUi: true,
  draftStoreMode: 'disabled',
  importAssetMode: 'localDataUrl',
  isIcpFreeRelease: false,
  isPublicDistribution: true,
  lockAccountPublicProfile: false,
  mornDraftComponentScope: 'showcase',
  profileId: 'oss',
  shareLinkMode: 'hidden',
  showAccountMenu: false,
  showAboutEnterpriseInfo: false,
  showAboutSupportQr: true,
  showDonationAction: false,
  showDraftSidebar: false,
  showEntitlementPanel: false,
  showFeedbackAction: false,
  showOssAiConfig: true,
  showSettingsAction: true,
  telemetryMode: 'noop',
});
