export type MornDraftComponentScope = 'showcase' | 'allPublicV2';
export type MornDraftReleaseConfig = {
  authMode: 'none';
  deliveryPolicyMode: 'publicAllOpen';
  disableAccountPlanQuotaUi: boolean;
  disableAccountPromoUi: boolean;
  disableReferralsUi: boolean;
  disableMcpUi: boolean;
  disableAiAssistUi: boolean;
  disableFeedbackUi: boolean;
  disablePaymentCheckout: boolean;
  disablePreviewDeliveryActions: boolean;
  disablePreviewFormatToolbar: boolean;
  disableSubscriptionUi: boolean;
  disableHostedLinkUi: true;
  draftStoreMode: 'disabled';
  importAssetMode: 'localDataUrl';
  isIcpFreeRelease: boolean;
  isPublicDistribution: true;
  lockAccountPublicProfile: boolean;
  mornDraftComponentScope: MornDraftComponentScope;
  profileId: string;
  shareLinkMode: 'hidden';
  showAccountMenu: false;
  showAboutEnterpriseInfo: boolean;
  showAboutSupportQr: boolean;
  showDonationAction: boolean;
  showDraftSidebar: false;
  showEntitlementPanel: false;
  showFeedbackAction: false;
  showOssAiConfig: true;
  showSettingsAction: true;
  telemetryMode: 'noop';
};
