export const HTML_PREVIEW_MIN_HEIGHT = 80;
export const HTML_PREVIEW_MAX_HEIGHT = 50000;
export const HTML_PREVIEW_SETTLE_MS = 150;
export const HTML_PREVIEW_HEIGHT_EPSILON = 4;
export const HTML_PREVIEW_WIDTH_EPSILON = 4;
export const HTML_PREVIEW_LOAD_TIMEOUT_MS = 900;
