import type React from 'react';

export const PREVIEW_CODE_FONT_SIZE = '13px';
export const PREVIEW_CODE_LINE_HEIGHT = 1.6;

export const MARKDOWN_CODE_BLOCK_CUSTOM_STYLE: React.CSSProperties = {
  margin: 0,
  padding: '12px 14px',
  overflowX: 'auto',
  border: 0,
  borderRadius: 0,
  background: 'var(--aad-code-bg)',
  color: 'var(--aad-syntax-text)',
  fontFamily: 'var(--aad-font-mono)',
  fontSize: PREVIEW_CODE_FONT_SIZE,
  lineHeight: PREVIEW_CODE_LINE_HEIGHT,
  overflowWrap: 'normal',
  boxShadow: 'none',
  tabSize: 2,
  textAlign: 'left',
  textIndent: 0,
  whiteSpace: 'pre',
  wordBreak: 'normal',
};

export const MORNDRAFT_PRISM_SYNTAX_STYLE = {
  'pre[class*="language-"]': {
    color: 'var(--aad-syntax-text)',
    background: 'var(--aad-code-bg)',
    fontFamily: 'var(--aad-font-mono)',
    fontSize: PREVIEW_CODE_FONT_SIZE,
    lineHeight: PREVIEW_CODE_LINE_HEIGHT,
    overflowWrap: 'normal',
    tabSize: 2,
    textAlign: 'left',
    textIndent: 0,
    textShadow: 'none',
    whiteSpace: 'pre',
    wordBreak: 'normal',
  },
  'code[class*="language-"]': {
    color: 'var(--aad-syntax-text)',
    background: 'transparent',
    fontFamily: 'var(--aad-font-mono)',
    fontSize: PREVIEW_CODE_FONT_SIZE,
    lineHeight: PREVIEW_CODE_LINE_HEIGHT,
    overflowWrap: 'normal',
    tabSize: 2,
    textAlign: 'left',
    textIndent: 0,
    textShadow: 'none',
    whiteSpace: 'pre',
    wordBreak: 'normal',
  },
  comment: { color: 'var(--aad-syntax-comment)' },
  prolog: { color: 'var(--aad-syntax-comment)' },
  doctype: { color: 'var(--aad-syntax-comment)' },
  cdata: { color: 'var(--aad-syntax-comment)' },
  punctuation: { color: 'var(--aad-syntax-punctuation)' },
  operator: { color: 'var(--aad-syntax-punctuation)' },
  entity: { color: 'var(--aad-syntax-punctuation)' },
  url: { color: 'var(--aad-syntax-punctuation)' },
  property: { color: 'var(--aad-syntax-property)' },
  tag: { color: 'var(--aad-syntax-property)' },
  constant: { color: 'var(--aad-syntax-property)' },
  symbol: { color: 'var(--aad-syntax-property)' },
  deleted: { color: 'var(--aad-syntax-property)' },
  boolean: { color: 'var(--aad-syntax-number)' },
  number: { color: 'var(--aad-syntax-number)' },
  selector: { color: 'var(--aad-syntax-property)' },
  'attr-name': { color: 'var(--aad-syntax-property)' },
  string: { color: 'var(--aad-syntax-string)' },
  char: { color: 'var(--aad-syntax-string)' },
  inserted: { color: 'var(--aad-syntax-string)' },
  builtin: { color: 'var(--aad-syntax-type)' },
  keyword: { color: 'var(--aad-syntax-keyword)' },
  'keyword.module': { color: 'var(--aad-syntax-keyword)' },
  'keyword.control-flow': { color: 'var(--aad-syntax-keyword)' },
  function: { color: 'var(--aad-syntax-function)' },
  'function.maybe-class-name': { color: 'var(--aad-syntax-function)' },
  'class-name': { color: 'var(--aad-syntax-type)' },
  'maybe-class-name': { color: 'var(--aad-syntax-type)' },
  parameter: { color: 'var(--aad-syntax-variable)' },
  variable: { color: 'var(--aad-syntax-variable)' },
  interpolation: { color: 'var(--aad-syntax-variable)' },
  imports: { color: 'var(--aad-syntax-variable)' },
  exports: { color: 'var(--aad-syntax-variable)' },
  'template-string': { color: 'var(--aad-syntax-string)' },
  'template-punctuation': { color: 'var(--aad-syntax-string)' },
  'interpolation-punctuation': { color: 'var(--aad-syntax-punctuation)' },
  'punctuation.interpolation-punctuation': { color: 'var(--aad-syntax-punctuation)' },
  regex: { color: 'var(--aad-syntax-regex)' },
  important: { color: 'var(--aad-syntax-regex)' },
  italic: { fontStyle: 'italic' },
  bold: { fontWeight: 700 },
} as const;
